### ISSUE TITLE
Improvement: Speed of the player

### ISSUE THREAD

**Issue by benda95280** [Saxavlax001/PECollide#1]
Hello,

Could it be possible to use the speed of the player ?

Idea is:
- If i'm moving a little, just 'stop' the player when collide (Don't know if it possible to cancel the event or just stop / prevent player to move in that way)
- if i'm at maxspeed, knockback 

Code i've found:
$speed = abs($player->getMotion()->x) + abs($player->getMotion->z);

**Comment by Saxavlax001** [comment]
Ok interesting,I'll try to do the second idea with maxspeed idk if I can do the first idea, but I can try that too if its possible.

**Comment by Saxavlax001** [comment]
@benda95280 idk a bit what I did,and I say that,because it does a different collision now,I mean when you're trying to collide with another player now,the first player stops for a very small time and then the first player feels the knock and second player takes knock too.

**Comment by Saxavlax001** [comment]
I may didn't explain it good,I hope you understood.

**Comment by benda95280** [comment]
PR send, sorry i'm new on Github and Pocketmine, i hope it will be good, but cannot test it :)

**Comment by benda95280** [comment]
Hum... merged before i've saw it ...
I've done a little modification

**Comment by Saxavlax001** [comment]
I merged your changes,they actually seem ok.

**Comment by benda95280** [comment]
I'm happy to read that :)

**Comment by Saxavlax001** [comment]
Lol,I was thinking it to merge it before months,but then I forgot it because of my server a bit and other things,also it poggit threw an issue,if you know something,your help is appreciated.

**Comment by benda95280** [comment]
Sorry wasn't able to understand your message :(

**Comment by Saxavlax001** [comment]
I mean I forgot to accept your pull request,so I accepted it,but poggit throws errors now for the plugin.

**Comment by benda95280** [comment]
Error is on :

_Problem found in axavlax001/pecollide/Main.php at line 14. :

Class saxavlax001\pecollide\PECollide does not have a constructor and must be instantiated without any parameters._

No recent change, but sems to be PHPStan.

Maybe change:
    $this->getServer()->getPluginManager()->registerEvents(new PECollide($this), $this);
TO
    $this->getServer()->getPluginManager()->registerEvents(new PECollide(), $this);

Sorry haven't time to try.

**Comment by Saxavlax001** [comment]
Ok I used your change and it worked,thanks.

**Comment by benda95280** [comment]
Cool !
